---
contentdir: "content"
layoutdir: "layouts"
publishdir: "public"
indexes:
  category: "categories"
baseurl: "https://l2a2m.github.io/hugo_gh_blog"
title: "Hugo Blog Original Experiment"
canonifyurls: true
theme: "Lanyon"
...
